### ISSUE TITLE
👀

### ISSUE THREAD

**Issue by spences10** [LearnInPublic/LearnInPublic.org#1]
Hey @sw-yx what's going on here?

It's checking my boxes!!

React Static ✔
Learning ✔
Netlify ✔

**Comment by swyxio** [comment]
haha. stuff i have ambitions for but no time to do 😢

**Comment by spences10** [comment]
If you want to fill me in on what you're doing I may be able to help.

I'd like to help if I can

**Comment by swyxio** [comment]
super appreciate the offer Scott!

honestly i dont quite know what it is yet. trying to figure it out. thats what takes time hehe. Basically im thinking about making a nonprofit that helps people learn in public like you and i do. but i dont really know how to be effective at doing that apart from kinda "leading by example". maybe having a community forum where people share what they're learning and get advice and encouragement. but that doesnt seem like "it" to me you know?

maybe im being too ambitious. i should just do the obvious thing.

**Comment by swyxio** [comment]
haha sorry to disappoint.

**Comment by spences10** [comment]
Np, you're a busy guy, I get it 👍
